import type { NextPage } from "next";
import Head from "next/head";
import Navbar from "../components/navbar";
import { trpc } from "../utils/trpc";

const Stocks: NextPage = () => {
	const hello = trpc.useQuery(["example.hello", { text: "from tRPC" }]);

	return (
		<>
			<Head>
				<title>Stonk Dashboard</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Navbar currentPage="stocks"/>
			<main className="container flex flex-col p-4">
				<div className="flex flex-wrap w-full justify-center p-4 gap-2">
				
				</div>
			</main>
		</>
	);
};

export default Stocks;