import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { trpc } from "../utils/trpc";

const Watchlists: NextPage = () => {
	const hello = trpc.useQuery(["example.hello", { text: "from tRPC" }]);

	return (
		<>
			<Head>
				<title>Stonk Dashboard</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<header className="flex p-4 justify-between w-full bg-gray-100">
				<div className="text-lg md:text-2xl font-extrabold text-gray-700 w-full md:w-1/2">
					<Link href="/">
						<a><span className="text-purple-300">Stonk </span> Dashboard</a>
					</Link>
				</div>
				<div className="flex flex-row justify-end md:w-1/2 w-full">
					<Link href="/stocks">
						<a className="text-lg md:text-2xl font-extrabold text-gray-700 pr-4">Stocks</a>
					</Link>
					<Link href="/watchlists">
						<a className="text-lg md:text-2xl font-extrabold text-gray-400 pr-4">Watchlists</a>
					</Link>
				</div>
			</header>
			<main className="container flex flex-col p-4">
				<div className="flex flex-wrap w-full justify-center p-4 gap-2">
				
				</div>
			</main>
		</>
	);
};

export default Watchlists;